### ISSUE TITLE
[Insight] Web applications should contain a favicon

### ISSUE THREAD

**Issue by davidyell** [davidyell/Learning-Symfony2#18]
**[in web/](https://github.com/davidyell/Learning-Symfony2/blob/master/web#L0)**

> No favicon found in the web root directory

```

web/
├── app.php
├── app_dev.php
└── robots.txt
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/68b0b820-5530-4bcc-8b60-3c1f3474051a/analyses/2?status=violations)_

**Comment by MatrixOfDeath** [comment]
I've got the same issue here even if i've got my favicon in the web repository
in ./
No favicon found in the web root directory
